name: GitHub Actions
run-name: ${{ github.actor }} is testing out ${{ github.repository }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.github/depandabot.yml'

jobs:
  Configure-Build-Install-Upload:
    strategy:
      matrix:
          os:
            - ubuntu-latest
            - macos-15
            - windows-latest

          include:
            - os: ubuntu-latest
              generator: 'Unix Makefiles'
              triplet: x64-linux

            - os: macos-15
              generator: 'Ninja Multi-Config'
              triplet: x64-osx

            - os: windows-latest
              generator: 'Visual Studio 17 2022'
              triplet: x64-windows

          build-type:
            - Debug

    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "Triggered by ${{ github.event_name }} on ${{ github.repository }} using ${{ github.ref}} branch and running on ${{ runner.os }}."

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.0'

      - name: Check out the Dear ImGui repository
        uses: actions/checkout@v5
        with:
          repository: ocornut/imgui
          show-progress: false
          path: imgui

      - name: Check out CMakeForImGui
        uses: actions/checkout@v5
        with:
          repository: adembudak/CMakeForImGui
          show-progress: false
          path: CMakeForImGui

      - name: Configure
        run: >
          cmake
          -S ${{ github.workspace }}/CMakeForImGui
          -B ${{ github.workspace }}/build
          -G "${{ matrix.generator }}"
          -D IMGUI_SOURCE_DIR=${{ github.workspace }}/imgui
          -D CMAKE_INSTALL_PREFIX=${{ github.workspace }}/installed.in.here

      - name: Build
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --config ${{ matrix.build-type }}

      - name: Fix install paths on Windows
        if: matrix.os == 'windows-latest'
        run: >
          (Get-Content -Path "${{ github.workspace }}\\build\\cmake_install.cmake")
          | ForEach-Object {$_ -replace 'D:\\a\\CMakeForImGui\\', 'D:/a/CMakeForImGui/'}
          | Set-Content -Path "${{ github.workspace }}\\build\\cmake_install.cmake"

      - name: Install
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --target install
          --config ${{ matrix.build-type }}

      - name: Remove build folder
        run: cmake -E rm -rf build

      - name: Checkout imgui_club
        uses: actions/checkout@v5
        with:
          repository: ocornut/imgui_club
          show-progress: false
          path: imgui_club

      - name: Checkout imgui_markdown
        uses: actions/checkout@v5
        with:
          repository: enkisoftware/imgui_markdown
          show-progress: false
          path: imgui_markdown

      - name: Checkout ImPlot
        uses: actions/checkout@v5
        with:
          repository: epezent/implot
          show-progress: false
          path: implot

      - name: Checkout ImPlot3D
        uses: actions/checkout@v5
        with:
          repository: brenocq/implot3d
          show-progress: false
          path: implot3d

      - name: Checkout ImGuiFileDialog
        uses: actions/checkout@v5
        with:
          repository: aiekick/ImGuiFileDialog
          show-progress: false
          path: ImGuiFileDialog

      - name: Check out CMakeForImGuiThirdParties
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          show-progress: false
          path: CMakeForImGuiThirdParties

      - name: List what is in here
        shell: bash
        run: ls -1 -p

      - name: Configure thirdparties
        run: >
          cmake
          -S ${{ github.workspace }}/CMakeForImGuiThirdParties
          -B ${{ github.workspace }}/build
          -G "${{ matrix.generator }}"
          -D DearImGui_DIR=${{ github.workspace }}/installed.in.here/lib/cmake/DearImGui
          -D CMAKE_INSTALL_PREFIX=${{ github.workspace }}/installed.in.there
          -D imgui_club=ON -D imgui_memory_editor=ON -D imgui_multicontext_compositor=ON -D imgui_threaded_rendering=ON -D IMGUI_CLUB_SOURCE_DIR=$PWD/imgui_club
          -D implot=ON -D IMPLOT_SOURCE_DIR=$PWD/implot
          -D imgui_markdown=ON -D IMGUI_MARKDOWN_SOURCE_DIR=$PWD/imgui_markdown
          -D implot3d=ON -D IMPLOT3D_SOURCE_DIR=$PWD/implot3d
          -D imguifiledialog=ON -D IMGUIFILEDIALOG_SOURCE_DIR=$PWD/ImGuiFileDialog

      - name: Build thirdparties
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --config ${{ matrix.build-type }}

      - name: Install thirdparties
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --target install
          --config ${{ matrix.build-type }}

      - name: Test the test
        shell: bash
        run: >
          cmake
          -S ${{ github.workspace }}/CMakeForImGuiThirdParties/test
          -B ${{ github.workspace }}/CMakeForImGuiThirdParties/test/build
          -G "${{ matrix.generator }}"
          -D imgui_club_DIR=${{ github.workspace }}/installed.in.there/lib/cmake/imgui_club
          -D imgui_markdown_DIR=${{ github.workspace }}/installed.in.there/lib/cmake/imgui_markdown
          -D ImPlot_DIR=${{ github.workspace }}/installed.in.there/lib/cmake/ImPlot
          -D ImPlot3D_DIR=${{ github.workspace }}/installed.in.there/lib/cmake/ImPlot3D
          -D ImGuiFileDialog_DIR=${{ github.workspace }}/installed.in.there/lib/cmake/ImGuiFileDialog
          ;
          cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }}

      - name: Upload
        uses: actions/upload-artifact@v4

        with:
          name: build.imgui-${{ matrix.tag }}.${{ matrix.os }}.${{ matrix.triplet }}.${{ matrix.build-type }}
          path: ${{ github.workspace }}/installed.in.there

      - run: echo "Job exited by ${{ job.status }}."
